import { Category } from "../models/category";
import { Criteria } from "../models/criteria";
import { Question } from "../models/question";

const questions =  [
  { "category": "Políticas Ambientais", "name": "A empresa tem uma política ambiental claramente definida?", "description": "", "required": true },
  { "category": "Políticas Ambientais", "name": "A empresa considera o impacto ambiental em suas decisões de negócios?", "description": "", "required": true },
  { "category": "Políticas Ambientais", "name": "A empresa tem uma política de conservação da biodiversidade?", "description": "", "required": false },
  { "category": "Políticas Ambientais", "name": "A empresa tem uma política de uso eficiente da terra?", "description": "", "required": false },
  { "category": "Emissão e energia", "name": "A empresa monitora e minimiza suas emissões de carbono?", "description": "", "required": true },
  { "category": "Emissão e energia", "name": "A empresa utiliza energia renovável em suas operações?", "description": "", "required": true },
  { "category": "Emissão e energia", "name": "A empresa tem metas claras e mensuráveis para reduzir suas emissões de gases de efeito estufa?", "description": "", "required": true },
  { "category": "Emissão e energia", "name": "A empresa realiza auditorias regulares de energia para identificar oportunidades de economia de energia?", "description": "", "required": true },
  { "category": "Emissão e energia", "name": "A empresa investe em tecnologias de captura e armazenamento de carbono para reduzir suas emissões?", "description": "", "required": false },
  { "category": "Gestão de Resíduos e Reciclagem", "name": "A empresa tem um programa eficaz de gestão de resíduos?", "description": "", "required": true },
  { "category": "Gestão de Resíduos e Reciclagem", "name": "A empresa tem um programa de reciclagem?", "description": "", "required": true },
  { "category": "Gestão de Resíduos e Reciclagem", "name": "A empresa tem um programa para minimizar a geração de resíduos em suas operações?", "description": "", "required": true },
  { "category": "Gestão de Resíduos e Reciclagem", "name": "A empresa tem iniciativas para reutilizar ou doar materiais que não são mais necessários para suas operações?", "description": "", "required": true },
  { "category": "Gestão de Resíduos e Reciclagem", "name": "A empresa tem um programa para reciclar ou compostar resíduos orgânicos?", "description": "", "required": false },
  { "category": "Conservação de Água", "name": "A empresa tem práticas de conservação de água?", "description": "", "required": true },
  { "category": "Conservação de Água", "name": "A empresa monitora e minimiza o uso de água e fertilizantes?", "description": "", "required": false },
  { "category": "Conservação de Água", "name": "A empresa tem metas claras e mensuráveis para reduzir seu uso de água?", "description": "", "required": true },
  { "category": "Conservação de Água", "name": "A empresa utiliza tecnologias de conservação de água, como sistemas de irrigação eficientes ou reciclagem de água?", "description": "", "required": false },
  { "category": "Conservação de Água", "name": "A empresa realiza auditorias regulares de água para identificar oportunidades de economia de água?", "description": "", "required": true },
  { "category": "Design e Ciclo de Vida do Produto", "name": "A empresa pensa sobre o que acontece com os produtos desde a criação até o descarte (ciclo de vida) quando está projetando-os?", "description": "", "required": true },
  { "category": "Design e Ciclo de Vida do Produto", "name": "A empresa considera o impacto ambiental de seus projetos?", "description": "", "required": true },
  { "category": "Design e Ciclo de Vida do Produto", "name": "A empresa considera a facilidade de desmontagem e reciclagem dos produtos em seu design?", "description": "", "required": true },
  { "category": "Design e Ciclo de Vida do Produto", "name": "A empresa utiliza materiais reciclados ou de fontes sustentáveis em seus produtos?", "description": "", "required": true },
  { "category": "Design e Ciclo de Vida do Produto", "name": "A empresa tem um programa para receber de volta produtos usados para reciclagem ou reutilização?", "description": "", "required": false },
  { "category": "Agricultura e Práticas Sustentáveis", "name": "A empresa pratica agricultura sustentável?", "description": "", "required": false },
  { "category": "Agricultura e Práticas Sustentáveis", "name": "A empresa utiliza tecnologias e práticas sustentáveis?", "description": "", "required": false },
  { "category": "Agricultura e Práticas Sustentáveis", "name": "A empresa utiliza práticas de agricultura regenerativa para melhorar a saúde do solo e sequestrar carbono?", "description": "", "required": false },
  { "category": "Agricultura e Práticas Sustentáveis", "name": "A empresa tem uma política para evitar o uso de pesticidas e fertilizantes sintéticos em suas operações agrícolas?", "description": "", "required": false },
  { "category": "Agricultura e Práticas Sustentáveis", "name": "A empresa promove a biodiversidade em suas operações agrícolas, por exemplo, através da rotação de culturas ou do plantio de culturas de cobertura?", "description": "", "required": false },
  { "category": "Privacidade do Cliente", "name": "A empresa tem uma política claramente definida de privacidade do cliente?", "description": "", "required": true },
  { "category": "Privacidade do Cliente", "name": "A empresa monitora e minimiza a coleta de dados do cliente?", "description": "", "required": true },
  { "category": "Privacidade do Cliente", "name": "A empresa tem uma política de não compartilhamento de dados do cliente?", "description": "", "required": true },
  { "category": "Privacidade do Cliente", "name": "A empresa tem um programa de resposta a violações de dados?", "description": "", "required": true },
  { "category": "Privacidade do Cliente", "name": "A empresa considera a privacidade do cliente em suas decisões de negócios?", "description": "", "required": true },
  { "category": "Informação ao Consumidor", "name": "A empresa garante que os clientes tenham acesso a informações sobre a composição dos produtos, seu uso correto e disposição?", "description": "", "required": true },
  { "category": "Informação ao Consumidor", "name": "A empresa ajuda os clientes a fazer escolhas bem fundamentadas através de uma comunicação de marketing justa e responsável?", "description": "", "required": true },
  { "category": "Informação ao Consumidor", "name": "A empresa considera os impactos positivos e negativos de seus produtos e serviços na comunicação de marketing?", "description": "", "required": true },
  { "category": "Segurança do Consumidor", "name": "A empresa teve algum incidente de saúde e segurança do consumidor?", "description": "", "required": true },
  { "category": "Segurança do Consumidor", "name": "A empresa tem uma política de segurança do consumidor?", "description": "", "required": true },
  { "category": "Segurança do Consumidor", "name": "A empresa realiza testes de segurança em seus produtos e serviços?", "description": "", "required": true },
  { "category": "Segurança do Consumidor", "name": "A empresa informa os consumidores sobre os possíveis riscos associados ao uso de seus produtos e serviços?", "description": "", "required": true },
  { "category": "Segurança do Consumidor", "name": "A empresa tem um processo para lidar com reclamações relacionadas à segurança do consumidor?", "description": "", "required": true },
  { "category": "Segurança do Consumidor", "name": "A empresa faz recall de produtos se identificar um risco à saúde ou segurança do consumidor?", "description": "", "required": true },
  { "category": "Políticas Públicas", "name": "A empresa faz contribuições financeiras para políticas públicas?", "description": "", "required": true },
  { "category": "Políticas Públicas", "name": "A empresa apoia políticas públicas que têm um impacto positivo na sociedade?", "description": "", "required": true },
  { "category": "Políticas Públicas", "name": "A empresa divulga publicamente suas contribuições para políticas públicas?", "description": "", "required": true },
  { "category": "Comunidade Local", "name": "As atividades da empresa impactam negativamente a comunidade local?", "description": "", "required": true },
  { "category": "Comunidade Local", "name": "A empresa identificou grupos vulneráveis que poderiam ser afetados negativamente por suas atividades?", "description": "", "required": true },
  { "category": "Comunidade Local", "name": "A empresa realiza avaliações de impacto social, incluindo avaliações de impacto de gênero?", "description": "", "required": true },
  { "category": "Comunidade Local", "name": "A empresa realiza avaliações de impacto ambiental e monitoramento contínuo?", "description": "", "required": true },
  { "category": "Comunidade Local", "name": "A empresa tem programas de desenvolvimento local baseados nas necessidades das comunidades locais?", "description": "", "required": true },
  { "category": "Comunidade Local", "name": "A empresa tem processos formais de queixas por parte de comunidades locais?", "description": "", "required": true },
  { "category": "Emprego e Condições de Trabalho", "name": "A empresa tem uma política clara de contratação, recrutamento e retenção de funcionários?", "description": "", "required": true },
  { "category": "Emprego e Condições de Trabalho", "name": "A empresa fornece condições de trabalho justas e seguras para seus funcionários?", "description": "", "required": true },
  { "category": "Emprego e Condições de Trabalho", "name": "A empresa respeita os direitos e obrigações legais em suas relações de emprego?", "description": "", "required": true },
  { "category": "Emprego e Condições de Trabalho", "name": "A empresa tem políticas para garantir o emprego e as condições de trabalho adequadas em sua cadeia de fornecedores?", "description": "", "required": true },
  { "category": "Emprego e Condições de Trabalho", "name": "A empresa segue as convenções e publicações relevantes da Organização Internacional do Trabalho, da Organização para a Cooperação e o Desenvolvimento Econômico e das Nações Unidas em relação ao emprego?", "description": "", "required": true },
  { "category": "Trabalho Forçado ou Análogo ao Escravo", "name": "A empresa tem uma política clara contra o trabalho forçado ou análogo ao escravo?", "description": "", "required": true },
  { "category": "Trabalho Forçado ou Análogo ao Escravo", "name": "A empresa realiza devida diligência para evitar e combater todas as formas de trabalho forçado ou análogo ao escravo em suas atividades?", "description": "", "required": true },
   { category: "Trabalho Forçado ou Análogo ao Escravo", name: "A empresa tem mecanismos para garantir que não contribua com o trabalho forçado ou análogo ao escravo ou se torne cúmplice no uso desse tipo de trabalho por meio de seus relacionamentos com outros, como fornecedores ou clientes?", description: "" },
  { "category": "Trabalho Forçado ou Análogo ao Escravo", "name": "A empresa tem mecanismos para garantir que não contribua com o trabalho forçado ou análogo ao escravo ou se torne cúmplice no uso desse tipo de trabalho por meio de seus relacionamentos com outros, como fornecedores ou clientes?", "description": "", "required": true },
  { "category": "Trabalho Forçado ou Análogo ao Escravo", "name": "A empresa tem políticas para proteger grupos vulneráveis, como mulheres e meninas, migrantes, trabalhadores de confecções e trabalhadores agrícolas, que são mais propensos a serem vítimas de trabalho forçado ou análogo ao escravo?", "description": "", "required": true },
  { "category": "Trabalho Forçado ou Análogo ao Escravo", "name": "A empresa tem um processo para lidar com reclamações ou violações dos direitos dos trabalhadores relacionadas ao trabalho forçado ou análogo ao escravo?", "description": "", "required": true },
  { "category": "Direitos Humanos", "name": "A empresa respeita os direitos humanos em suas operações?", "description": "", "required": true },
  { "category": "Direitos Humanos", "name": "A empresa tem políticas para prevenir violações dos direitos humanos?", "description": "", "required": true },
  { "category": "Direitos Humanos", "name": "A empresa tem um processo para lidar com reclamações ou violações dos direitos humanos?", "description": "", "required": true },
  { "category": "Direitos Humanos", "name": "A empresa tem um código de conduta que inclui o respeito aos direitos humanos?", "description": "", "required": true },
  { "category": "Direitos Humanos", "name": "A empresa realiza treinamentos regulares para seus funcionários sobre os direitos humanos?", "description": "", "required": true },
  { "category": "Diversidade e Igualdade", "name": "A empresa promove a diversidade e a igualdade em suas operações?", "description": "", "required": true },
  { "category": "Diversidade e Igualdade", "name": "A empresa tem políticas para prevenir a discriminação no local de trabalho?", "description": "", "required": true },
  { "category": "Diversidade e Igualdade", "name": "A empresa tem um processo para lidar com reclamações ou violações relacionadas à diversidade e igualdade?", "description": "", "required": true },
  { "category": "Diversidade e Igualdade", "name": "A empresa tem metas claras e mensuráveis para promover a diversidade e a igualdade em suas operações?", "description": "", "required": true },
  { "category": "Diversidade e Igualdade", "name": "A empresa realiza treinamentos regulares para seus funcionários sobre diversidade e igualdade?", "description": "", "required": true },
  { "category": "Estrutura e Ética de Governança", "name": "A empresa tem uma estrutura de governança claramente definida?", "description": "", "required": true },
  { "category": "Estrutura e Ética de Governança", "name": "A empresa segue altos padrões de ética empresarial?", "description": "", "required": true },
  { "category": "Estrutura e Ética de Governança", "name": "A empresa é transparente em suas operações e relatórios financeiros?", "description": "", "required": true },
  { "category": "Estrutura e Ética de Governança", "name": "A remuneração dos executivos está alinhada com o desempenho da empresa?", "description": "", "required": true },
  { "category": "Estrutura e Ética de Governança", "name": "A empresa tem um processo de tomada de decisão transparente?", "description": "", "required": true },
  { "category": "Diversidade do Conselho", "name": "O conselho da empresa é composto por uma variedade de gêneros?", "description": "", "required": true },
  { "category": "Diversidade do Conselho", "name": "O conselho da empresa é composto por uma variedade de nacionalidades?", "description": "", "required": true },
  { "category": "Diversidade do Conselho", "name": "O conselho da empresa possui uma variedade de habilidades e áreas de expertise?", "description": "", "required": true },
  { "category": "Diversidade do Conselho", "name": "A empresa tem uma política para garantir a diversidade de gênero no conselho?", "description": "", "required": true },
  { "category": "Diversidade do Conselho", "name": "A empresa tem uma política para garantir a diversidade de nacionalidade no conselho?", "description": "", "required": true },
  { "category": "Políticas de Governança Corporativa", "name": "A empresa possui um conjunto claramente definido de políticas de governança corporativa?", "description": "", "required": true },
  { "category": "Políticas de Governança Corporativa", "name": "As políticas de governança corporativa da empresa são transparentes e facilmente acessíveis aos stakeholders?", "description": "", "required": true },
  { "category": "Políticas de Governança Corporativa", "name": "As políticas de governança corporativa da empresa incluem diretrizes para a distribuição de poderes e responsabilidades entre os diversos órgãos da entidade?", "description": "", "required": true },
  { "category": "Políticas de Governança Corporativa", "name": "As políticas de governança corporativa da empresa promovem a transparência e a confiança entre todas as partes interessadas?", "description": "", "required": true },
  { "category": "Políticas de Governança Corporativa", "name": "A empresa revisa e atualiza regularmente suas políticas de governança corporativa para garantir sua eficácia?", "description": "", "required": true },
  { "category": "Remuneração Variável", "name": "A empresa tem uma política de remuneração variável para os diretores?", "description": "", "required": true },
  { "category": "Remuneração Variável", "name": "A remuneração variável dos diretores está vinculada a métricas de desempenho?", "description": "", "required": true },
  { "category": "Remuneração Variável", "name": "As métricas de desempenho usadas para determinar a remuneração variável dos diretores são transparentes e facilmente acessíveis aos stakeholders?", "description": "", "required": true },
  { "category": "Remuneração Variável", "name": "A empresa revisa e atualiza regularmente suas políticas de remuneração variável para garantir sua eficácia?", "description": "", "required": true },
  { "category": "Satisfação do Cliente", "name": "Os clientes estão satisfeitos com a qualidade dos produtos ou serviços da empresa?", "description": "", "required": true },
  { "category": "Satisfação do Cliente", "name": "A empresa responde efetivamente às reclamações e feedback dos clientes?", "description": "", "required": true },
  { "category": "Satisfação do Cliente", "name": "A empresa faz pesquisas regulares de satisfação do cliente?", "description": "", "required": true },
  { "category": "Satisfação do Cliente", "name": "A empresa usa o feedback do cliente para melhorar seus produtos ou serviços?", "description": "", "required": true },
  { "category": "Satisfação do Cliente", "name": "A empresa tem uma política de atendimento ao cliente que prioriza a satisfação do cliente?", "description": "", "required": true },
  { "category": "Satisfação do Funcionário", "name": "Os funcionários estão satisfeitos com o ambiente de trabalho na empresa?", "description": "", "required": true },
  { "category": "Satisfação do Funcionário", "name": "A empresa responde efetivamente às preocupações e feedback dos funcionários?", "description": "", "required": true },
  { "category": "Satisfação do Funcionário", "name": "A empresa realiza pesquisas regulares de satisfação do funcionário?", "description": "", "required": true },
  { "category": "Satisfação do Funcionário", "name": "A empresa usa o feedback do funcionário para melhorar suas políticas e práticas de trabalho?", "description": "", "required": true },
  { "category": "Satisfação do Funcionário", "name": "A empresa tem uma política de recursos humanos que prioriza a satisfação do funcionário?", "description": "", "required": true },
  { "category": "Combate à Corrupção", "name": "A empresa tem uma política clara de combate à corrupção?", "description": "", "required": true },
  { "category": "Combate à Corrupção", "name": "A empresa tem mecanismos para prevenir práticas de corrupção, como suborno, fraude, extorsão e lavagem de dinheiro?", "description": "", "required": true },
  { "category": "Combate à Corrupção", "name": "A empresa tem um processo para lidar com a oferta ou recebimento de presentes, empréstimos, comissões, recompensas ou outras vantagens que possam induzir ações desonestas ou ilegais?", "description": "", "required": true },
  { "category": "Combate à Corrupção", "name": "A empresa tem políticas para prevenir práticas como apropriação indébita, tráfico de influência, abuso de função, enriquecimento ilícito, ocultação e obstrução da justiça?", "description": "", "required": true },
  { "category": "Combate à Corrupção", "name": "A empresa demonstra um compromisso com a integridade, a governança e as práticas empresariais responsáveis para combater a corrupção?", "description": "", "required": true },
  { "category": "Cadeia de Fornecedores", "name": "A empresa possui uma política de governança claramente definida para a seleção de novos fornecedores?", "description": "", "required": true },
  { "category": "Cadeia de Fornecedores", "name": "A empresa implementou processos de governança para identificar e avaliar impactos sociais negativos significativos na cadeia de fornecedores?", "description": "", "required": true },
  { "category": "Cadeia de Fornecedores", "name": "A empresa estabelece expectativas em contratos com fornecedores para promover a prevenção, mitigação e reparação de impactos sociais negativos?", "description": "", "required": true },
  { "category": "Cadeia de Fornecedores", "name": "A empresa incentiva e recompensa fornecedores que previnem, mitigam e reparam impactos sociais significativos como parte de sua governança corporativa?", "description": "", "required": true },
  { "category": "Cadeia de Fornecedores", "name": "A empresa tem sistemas de governança para avaliar impactos negativos potenciais do encerramento da relação com um fornecedor?", "description": "", "required": true }
];

export const createQuestions = async () => {
  const createdQuestions = await Promise.all(
    questions.map(async ({ name, category, description, required }) => {
      const categoryQyuestion = await Category.findOne({
        where: { name: category },
      });
      if (categoryQyuestion) {
        await Question.create({
          name: name,
          description,
          categoryId: categoryQyuestion.id,
          category: categoryQyuestion,
          required: required
        });
      }
    })
  );
  return createdQuestions;
};
